   
release:
  stage: build
  only:
    - master-ifsp
  image: alpine:3.11
  script:
    - apk --no-cache add zip unzip curl
    - mkdir /public
    - mv /builds/ti/moodle-integrador-suap /builds/ti/suap/
    - rm -rf /builds/ti/moodle-integrador-suap/.git
    - zip -r /public/block_suap_ifsp.zip /builds/ti/suap/*
    - mv /builds/ti/suap/ /builds/ti/moodle-integrador-suap
    - curl -F 'blockfile=@/public/block_suap_ifsp.zip' 10.119.50.99:94/block_suap.php
